language: ruby
rvm:
  - 2.6.3

sudo: false
branches:
  only:
    - src

cache:
  bundler: true


script: ./buildToMaster
env:
  global:
    - ENCRYPTION_LABEL: "0ddd2445e49f"
    - COMMIT_AUTHOR_EMAIL: "donald_pinckney@icloud.com"

